INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Carrot'	,	'Greene'	,	'Meet Carrot, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Carrot''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Carrot believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Carrot, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'CarrotGreene@email.com'	,	'Password123'	,	FALSE);


INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Kale'	,	'Turnipson'	,	'Meet Kale, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Kale''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Kale believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Kale, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'KaleTurnipson@email.com'	,	'Password124'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Broccoli'	,	'Radish'	,	'Meet Broccoli, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Broccoli''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Broccoli believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Broccoli, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'BroccoliRadish@email.com'	,	'Password125'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Zucchini'	,	'Pepper'	,	'Meet Zucchini , a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Zucchini ''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Zucchini  believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Zucchini , the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'ZucchiniPepper@email.com'	,	'Password126'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Aubergine'	,	'Smith'	,	'Meet Aubergine, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Aubergine''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Aubergine believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Aubergine, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'AubergineSmith@email.com'	,	'Password127'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Cabbage'	,	'Carver'	,	'Meet Cabbage, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Cabbage''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Cabbage believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Cabbage, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'CabbageCarver@email.com'	,	'Password128'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Squash'	,	'Greenfield'	,	'Meet Squash, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Squash''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Squash believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Squash, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'SquashGreenfield@email.com'	,	'Password129'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Leek'	,	'Turnipseed'	,	'Meet Leek, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Leek''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Leek believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Leek, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'LeekTurnipseed@email.com'	,	'Password130'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Onion'	,	'Beanstalk'	,	'Meet Onion, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Onion''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Onion believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Onion, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'OnionBeanstalk@email.com'	,	'Password131'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Rutabaga'	,	'Harvest'	,	'Meet Rutabaga, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Rutabaga''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Rutabaga believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Rutabaga, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'RutabagaHarvest@email.com'	,	'Password132'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Celery'	,	'Greensmith'	,	'Meet Celery, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Celery''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Celery believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Celery, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'CeleryGreensmith@email.com'	,	'Password133'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Spinach'	,	'Parsnip'	,	'Meet Spinach, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Spinach''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Spinach believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Spinach, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'SpinachParsnip@email.com'	,	'Password134'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Tomato'	,	'Rutabaga'	,	'Meet Tomato, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Tomato''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Tomato believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Tomato, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'TomatoRutabaga@email.com'	,	'Password135'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Potato'	,	'Sproutman'	,	'Meet Potato, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Potato''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Potato believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Potato, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'PotatoSproutman@email.com'	,	'Password136'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Berry'	,	'Greenfield'	,	'Meet Berry, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Berry''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Berry believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Berry, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'BerryGreenfield@email.com'	,	'Password137'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Melon'	,	'Turnipson'	,	'Meet Melon, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Melon''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Melon believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Melon, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'MelonTurnipson@email.com'	,	'Password138'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Clementine'	,	'Radish'	,	'Meet Clementine, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Clementine''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Clementine believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Clementine, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'ClementineRadish@email.com'	,	'Password139'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Kiwi'	,	'Carroton'	,	'Meet Kiwi, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Kiwi''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Kiwi believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Kiwi, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'KiwiCarroton@email.com'	,	'Password140'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Plum'	,	'Veggieville'	,	'Meet Plum, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Plum''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Plum believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Plum, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'PlumVeggieville@email.com'	,	'Password141'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Apple'	,	'Rutabaga'	,	'Meet Apple, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Apple''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Apple believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Apple, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'AppleRutabaga@email.com'	,	'Password142'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Tomato'	,	'Peartree'	,	'Meet Tomato, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Tomato''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Tomato believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Tomato, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'TomatoPeartree@email.com'	,	'Password143'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Peach'	,	'Beanbloom'	,	'Meet Peach, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Peach''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Peach believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Peach, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'PeachBeanbloom@email.com'	,	'Password144'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Spinach'	,	'Orchardson'	,	'Meet Spinach, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Spinach''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Spinach believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Spinach, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'SpinachOrchardson@email.com'	,	'Password145'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Citrus'	,	'Cabbington'	,	'Meet Citrus, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Citrus''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Citrus believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Citrus, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'CitrusCabbington@email.com'	,	'Password146'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Mango'	,	'Celery'	,	'Meet Mango, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Mango''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Mango believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Mango, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'MangoCelery@email.com'	,	'Password147'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Zucchini'	,	'Berryman'	,	'Meet Zucchini, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Zucchini''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Zucchini believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Zucchini, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'ZucchiniBerryman@email.com'	,	'Password148'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Blueberry'	,	'Greensmith'	,	'Meet Blueberry, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Blueberry''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Blueberry believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Blueberry, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'BlueberryGreensmith@email.com'	,	'Password149'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Grapefruit'	,	'Parsnip'	,	'Meet Grapefruit, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Grapefruit''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Grapefruit believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Grapefruit, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'GrapefruitParsnip@email.com'	,	'Password150'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Strawberry'	,	'Leekson'	,	'Meet Strawberry, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Strawberry''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Strawberry believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Strawberry, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'StrawberryLeekson@email.com'	,	'Password151'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Pineapple'	,	'Beanfield'	,	'Meet Pineapple, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Pineapple''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Pineapple believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Pineapple, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'PineappleBeanfield@email.com'	,	'Password152'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Orange'	,	'Rutabagason'	,	'Meet Orange, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Orange''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Orange believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Orange, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'OrangeRutabagason@email.com'	,	'Password153'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Guava'	,	'Carrothorn'	,	'Meet Guava, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Guava''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Guava believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Guava, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'GuavaCarrothorn@email.com'	,	'Password154'	,	FALSE);

INSERT INTO users (first_name, last_name, description, email, password, admin_user)
VALUES (	'Dragon'	,	'Fruitvegetable'	,	'Meet Dragon, a devoted gardener at our community plot, who exudes an infectious passion for cultivating the earth. Dragon''s love for gardening sprouted from a tiny balcony garden in their apartment, where a single potted plant ignited a fervor for nurturing life. Now, as they tend to their verdant oasis in the community garden, they find joy in the simple act of coaxing seeds into vibrant blooms. Dragon believes that their garden plot is more than just a collection of plants; it''s a living testament to the beauty of patience, resilience, and the ever-renewing cycle of growth. they encourage others to visit, not just to witness the kaleidoscope of colors and shapes, but to experience the therapeutic rhythm of gardening. According to Dragon, the garden isn''t just about vegetables; it''s a sanctuary where people can escape, reconnect with nature, and discover the profound satisfaction that comes from nurturing the land in a shared space.'	,	'DragonFruitvegetable@email.com'	,	'Password155'	,	FALSE);