-- DROP and CREATE plantedPlants TABLE
DROP TABLE IF EXISTS plantedPlants CASCADE;

CREATE TABLE plantedPlants (
plantedPlants_id SERIAL PRIMARY KEY NOT NULL,
plot_id INT,
FOREIGN KEY(plot_id) REFERENCES plots ON DELETE CASCADE,
plant_id INT,
FOREIGN KEY(plant_id) REFERENCES plants ON DELETE CASCADE
);  